#!/usr/bin/env bash
# Builds the native uBO cosmetic + scriptlet engine modules from uBlock Origin
# source (cosmetic-filtering.js + scriptlet-filtering-core.js and their closure):
#   UBOCosmetic.sys.mjs          - the bundled engine (esbuild)
#   UBOCosmeticResources.sys.mjs - uBO scriptlet resource text (module string)
# Outputs land in the source tree at toolkit/components/content-classifier/ and
# are captured in patches/native/native-ubo-cosmetic.patch.
# RUN ON A NETWORKED MACHINE (clones uBO; npm install; needs node + npx esbuild).
#   bash scripts/vendor-ubo/build-cosmetic.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
TREE="neonwolf-$(cat "$REPO/version")-$(cat "$REPO/release")"
OUT="$REPO/$TREE/toolkit/components/content-classifier"

echo "==> cloning uBlock Origin + installing @gorhill/ubo-core"
git clone --quiet --depth 1 https://github.com/gorhill/uBlock "$WORK/uBlock"
( cd "$WORK" && npm install --silent @gorhill/ubo-core esbuild )

echo "==> vendoring cosmetic closure from the clone"
SRC="$WORK/uBlock/src/js"
mkdir -p "$WORK/ubo-src" "$WORK/lib/publicsuffixlist"
for f in cosmetic-filtering.js scriptlet-filtering-core.js redirect-engine.js \
         static-ext-filtering-db.js mrucache.js uri-utils.js text-utils.js \
         redirect-resources.js; do
  cp "$SRC/$f" "$WORK/ubo-src/"
done
cp "$WORK/uBlock/src/lib/publicsuffixlist/publicsuffixlist.js" "$WORK/lib/publicsuffixlist/"
cp "$WORK/uBlock/src/lib/punycode.js" "$WORK/lib/"
cp "$HERE/vapi-stub.js" "$WORK/ubo-src/"
cp "$HERE/cosmetic-entry.js" "$WORK/"
# Inert stubs for the two browser modules uBO's cosmetic engine imports.
cat > "$WORK/ubo-src/background.js" <<'STUB'
const µb = { hiddenSettings: { allowGenericProceduralFilters: false } };
export default µb;
STUB
cat > "$WORK/ubo-src/logger.js" <<'STUB'
const logger = { writeOne() {}, enabled: false };
export default logger;
STUB

echo "==> bundling UBOCosmetic.sys.mjs"
( cd "$WORK" && npx esbuild cosmetic-entry.js --bundle --format=esm \
    --platform=browser --alias:ubo-src=./ubo-src \
    --banner:js='/* Neonwolf: uBlock Origin cosmetic + scriptlet filtering engine
 * (cosmetic-filtering.js + scriptlet-filtering-core.js), bundled to run
 * natively in Firefox privileged JS. GPL-3.0-or-later. "powered by uBlock"
 * https://github.com/gorhill/uBlock
 * Generated by scripts/vendor-ubo/build-cosmetic.sh -- do not edit by hand. */' \
    --outfile="$OUT/UBOCosmetic.sys.mjs" )

echo "==> generating UBOCosmeticResources.sys.mjs"
( cd "$WORK" && node "$HERE/gen-resources.mjs" )
node -e '
const fs = require("fs");
const txt = fs.readFileSync(process.argv[1], "utf8");
fs.writeFileSync(process.argv[2],
  "/* Neonwolf: uBO scriptlet/redirect resource text for the cosmetic engine\n" +
  " * (redirect-engine.resourcesFromString format). Generated by\n" +
  " * scripts/vendor-ubo/build-cosmetic.sh. */\nexport default " +
  JSON.stringify(txt) + ";\n");
' "$WORK/ubo-resources.txt" "$OUT/UBOCosmeticResources.sys.mjs"

echo "==> done:"
ls -la "$OUT"/UBOCosmetic.sys.mjs "$OUT"/UBOCosmeticResources.sys.mjs
echo "Remember to regenerate patches/native/native-ubo-cosmetic.patch if these changed."
