#!/usr/bin/env bash
# Builds the native uBO network engine modules from @gorhill/ubo-core:
#   UBOSnfe.sys.mjs      - StaticNetFilteringEngine bundled for Firefox
#                          privileged JS (esbuild, Node built-ins removed,
#                          setTimeout shimmed via Timer.sys.mjs)
#   UBOPslSelfie.sys.mjs - public suffix list selfie the engine needs
# Outputs land in the source tree at toolkit/components/content-classifier/
# and are then captured in patches/native/native-ubo-snfe.patch.
# RUN ON A NETWORKED MACHINE (npm install; needs node + npx esbuild).
#   bash scripts/vendor-ubo/build-snfe.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
TREE="neonwolf-$(cat "$REPO/version")-$(cat "$REPO/release")"
OUT="$REPO/$TREE/toolkit/components/content-classifier"

echo "==> installing @gorhill/ubo-core"
( cd "$WORK" && npm install --silent @gorhill/ubo-core esbuild )

echo "==> bundling UBOSnfe.sys.mjs"
cp "$HERE/snfe-entry.js" "$HERE/timers-shim.js" "$WORK/"
( cd "$WORK" && npx esbuild snfe-entry.js --bundle --format=esm \
    --platform=browser --inject:./timers-shim.js \
    --banner:js='/* Neonwolf: uBlock Origin static network filtering engine (@gorhill/ubo-core),
 * bundled to run natively in Firefox privileged JS. GPL-3.0-or-later.
 * "powered by uBlock" -- https://github.com/gorhill/uBlock
 * Generated by scripts/vendor-ubo/build-snfe.sh -- do not edit by hand. */' \
    --outfile="$OUT/UBOSnfe.sys.mjs" )

echo "==> generating UBOPslSelfie.sys.mjs"
node -e '
const fs = require("fs");
const json = fs.readFileSync(process.argv[1], "utf8");
fs.writeFileSync(process.argv[2],
  "/* Neonwolf: public suffix list selfie for the uBO SNFE (from @gorhill/ubo-core\n" +
  " * build/publicsuffixlist.json). Generated by scripts/vendor-ubo/build-snfe.sh. */\n" +
  "export default " + json + ";\n");
' "$WORK/node_modules/@gorhill/ubo-core/build/publicsuffixlist.json" \
  "$OUT/UBOPslSelfie.sys.mjs"

echo "==> done:"
ls -la "$OUT"/UBOSnfe.sys.mjs "$OUT"/UBOPslSelfie.sys.mjs
echo "Remember to regenerate patches/native/native-ubo-snfe.patch if these changed."
