#!/usr/bin/env python3
"""Vendor the scriptlet/redirect resource bundle for Neonwolf's native M2
scriptlet injection (##+js()) and $redirect.

WHY this source: adblock 0.12.1's own `resource_assembler::assemble_scriptlet_resources`
only parses uBlock Origin's *deprecated* line-based scriptlet format; current uBO
ships an ES-module format the assembler cannot ingest. Brave's `adblock-resources`
project generates the bundle WITH adblock-rust itself, emitting exactly the
`Resource` JSON the engine deserializes (name/aliases/kind/content(base64)/
dependencies/permission). It is the canonical, format-correct, current source.

RUN THIS ON A NETWORKED MACHINE. It writes assets/ubo-resources.json. Then the
build packages it to <GreD>/browser/defaults/settings/ubo-resources.json and the
ContentClassifierService loads it into every engine via use_resources().

Usage:
    python3 scripts/fetch-ubo-resources.py            # fetch + validate + write
    python3 scripts/fetch-ubo-resources.py --check FILE  # just validate a file
"""
import argparse
import base64
import json
import sys
import urllib.request

# Canonical adblock-format resource bundle, generated by adblock-rust.
# Pin a known-good ref rather than a moving branch for reproducibility.
SOURCE_URL = (
    "https://raw.githubusercontent.com/brave/adblock-resources/master/dist/resources.json"
)

# A few resources that MUST be present for the d3ward script_ads/script_pagead
# checks and common anti-adblock defeat. Sanity gate, not exhaustive.
EXPECTED = [
    "abort-on-property-read.js",
    "set-constant.js",
    "noeval.js",
    "google-analytics_analytics.js",  # neutered GA redirect resource
    "noopjs",  # common redirect alias
]

VALID_MIMES = {
    "application/javascript", "fn/javascript", "text/css", "text/html",
    "text/plain", "image/gif", "image/png", "application/json",
    "audio/mp3", "video/mp4", "text/xml", "application/octet-stream",
}


def validate(resources):
    """Validate the bundle matches adblock 0.12.1's Resource schema closely
    enough that serde_json::from_str::<Vec<Resource>> will succeed, and that the
    critical scriptlets are present. Returns (ok, problems)."""
    problems = []
    if not isinstance(resources, list) or not resources:
        return False, ["top level is not a non-empty JSON array"]

    names = set()
    for i, r in enumerate(resources):
        if not isinstance(r, dict):
            problems.append(f"[{i}] not an object")
            continue
        for req in ("name", "kind", "content"):
            if req not in r:
                problems.append(f"[{i}] missing required field '{req}'")
        kind = r.get("kind")
        # ResourceType: {"mime": "<mimetype>"} or "template"
        if isinstance(kind, dict):
            mime = kind.get("mime")
            if mime not in VALID_MIMES:
                problems.append(f"[{r.get('name','?')}] unknown mime '{mime}'")
        elif kind != "template":
            problems.append(f"[{r.get('name','?')}] unexpected kind {kind!r}")
        # content must be valid base64
        try:
            base64.b64decode(r.get("content", ""), validate=True)
        except Exception:
            problems.append(f"[{r.get('name','?')}] content is not valid base64")
        names.add(r.get("name"))
        for a in r.get("aliases", []) or []:
            names.add(a)

    missing = [e for e in EXPECTED if e not in names]
    if missing:
        problems.append(f"missing expected resources: {missing}")
    return (len([p for p in problems if 'unknown mime' not in p]) == 0), problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", metavar="FILE", help="validate an existing bundle file and exit")
    ap.add_argument("--out", default="assets/ubo-resources.json")
    ap.add_argument("--url", default=SOURCE_URL)
    args = ap.parse_args()

    if args.check:
        resources = json.load(open(args.check))
    else:
        print(f"fetching {args.url}", flush=True)
        with urllib.request.urlopen(args.url, timeout=30) as resp:
            raw = resp.read()
        resources = json.loads(raw)

    ok, problems = validate(resources)
    print(f"resources: {len(resources)}; validation: {'PASS' if ok else 'FAIL'}")
    for p in problems:
        print("  -", p)
    if not ok:
        sys.exit("bundle failed validation; do NOT ship it. Check the source/format.")

    if not args.check:
        with open(args.out, "w") as f:
            # compact, deterministic
            json.dump(resources, f, separators=(",", ":"), sort_keys=False)
        print(f"wrote {args.out} ({len(resources)} resources)")
        print("NEXT: package it (mirror the lists dump) so it lands at")
        print("  <GreD>/browser/defaults/settings/ubo-resources.json")
        print("  i.e. add FINAL_TARGET_FILES.defaults.settings += ['ubo-resources.json']")
        print("  with the file copied into the tree by neonwolf-patches.py, then rebuild.")
        print("Then validate: d3ward script_ads / script_pagead should flip true.")


if __name__ == "__main__":
    main()
